---           
apiVersion: apps/v1
kind: Deployment
metadata:
  name: solr
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
     run: solr
  template:
    metadata:
      labels:
        run: solr
    spec:
      nodeName: docker02
      containers:
      - name: solr
        image: moravianlibrary/solr:6.3.0
        ports:
        - containerPort: 8983
          name: http
---           
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fcrepo
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
     run: fcrepo
  template:
    metadata:
      labels:
        run: fcrepo
    spec:
      nodeName: docker02
      containers:
      - name: fcrepo
        image: moravianlibrary/fcrepo:3.8.1
        env:
          - name: "FEDORA_PASSWORD"
            value: "fedoraAdmin"
          - name: "FEDORA_DB_JDBC_URL"
            value: "jdbc:postgresql://fedora-postgres:5432/fedora3"
          - name: "FEDORA_DB_USER"
            value: "fedoraAdmin"
          - name: "FEDORA_DB_PASSWORD"
            value: "fedoraAdmin"
          - name: "RITRIPLES_DB_JDBC_URL"
            value: "jdbc:postgresql://ri-triples-postgres:5432/riTriples"
          - name: "RITRIPLES_DB_USER"
            value: "fedoraAdmin"
          - name: "RITRIPLES_DB_PASSWORD"
            value: "fedoraAdmin"
        ports:
        - containerPort: 8080
          name: http
---
apiVersion: v1               
kind: Service                
metadata:                    
  name: fcrepo 
  labels:                    
    run: fcrepo
spec:                        
  type: ClusterIP
  selector:                   
    run: fcrepo
  ports:                     
  - name: http               
    port: 8080               
    targetPort: 8080
    protocol: TCP
---
apiVersion: v1               
kind: Service                
metadata:                    
  name: solr 
  labels:                    
    run: solr
spec:                        
  type: ClusterIP
  selector:                   
    run: solr
  ports:                     
  - name: http               
    port: 8983               
    targetPort: 8983
    protocol: TCP   
---           
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kramerius
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
     run: kramerius
  template:
    metadata:
      labels:
        run: kramerius
    spec:
      nodeName: docker02
      containers:
      - name: kramerius
        image: moravianlibrary/kramerius    
        env:
          - name: "fedoraHost"
            value: "http://fcrepo:8080/fedora"
          - name: "fedoraUser"
            value: "fedoraAdmin"
          - name: "fedoraPass"
            value: "fedoraAdmin"
          - name: "fedora3_connectionURL"
            value: "jdbc:postgresql://fedora-postgres:5432/fedora3"
          - name: "fedora3_connectionUser"
            value: "fedoraAdmin"
          - name: "fedora3_connectionPass"
            value: "fedoraAdmin"
          - name: "kramerius_connectionURL"
            value: "jdbc:postgresql://kramerius-postgres:5432/kramerius"
          - name: "kramerius_connectionUser"
            value: "fedoraAdmin"
          - name: "kramerius_connectionPass"
            value: "fedoraAdmin"
          - name: "driver_fedora_mpt_jdbc_url"
            value: "jdbc:postgresql://ri-triples-postgres:5432/riTriples"
          - name: "driver_fedora_mpt_jdbc_user"
            value: "fedoraAdmin"
          - name: "driver_fedora_mpt_jdbc_password"
            value: "fedoraAdmin"
          - name: "solrHost"
            value: "http://solr:8983/solr/kramerius"
          - name: "applicationUrl"
            value: "http://localhost:8080/search"
        ports:
        - containerPort: 8080
          name: http
        volumeMounts:
        - name: kramerius-import
          mountPath: /opt/app-root/src/.kramerius4/import     
      volumes:
       - name: kramerius-import
         hostPath:
            path: /data/import     
---
apiVersion: v1               
kind: Service                
metadata:                    
  name: kramerius 
  labels:                    
    run: kramerius
spec:                        
  type: NodePort
  selector:                   
    run: kramerius
  ports:  
    - port: 8080
      nodePort: 30003
      name: http  

