---           
apiVersion: apps/v1
kind: Deployment
metadata:
  name: imgserver
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
     run: imgserver
  template:
    metadata:
      labels:
        run: imgserver
    spec:
      nodeName: docker02
      containers:
      - name: imgserver
        image: moravianlibrary/iipsrv-nginx:mzk
        env:
          - name: "VIRTUAL_HOST"
            value: "docker02.nkp.cz/"   
          - name: "LETSENCRYPT_HOST"
            value: "docker02.nkp.cz/"   
          - name: "LETSENCRYPT_EMAIL"
            value: "andrej.chmelo@cgi.com"   
          - name: "HTTPS_METHOD"
            value: "noredirect"   
        ports:
        - containerPort: 80
          name: tcp
        volumeMounts:
        - name: imgserver-import
          mountPath: /var/www/imageserver/data       
      - name: imgsrv
        image: moravianlibrary/iipsrv-imageserver    
        volumeMounts:
        - name: imgserver-import
          mountPath: /data     
        ports:
        - containerPort: 9000
          name: http   
      volumes:
       - name: imgserver-import
         hostPath:
            path: /data/imgserver
---
apiVersion: v1               
kind: Service                
metadata:                    
  name: imgserver 
  labels:                    
    run: imgserver
spec:                        
  type: NodePort
  selector:                   
    run: imgserver
  ports:  
    - port: 80
      nodePort: 30006
      name: tcp 
    - port: 9000
      nodePort: 30008
      name: tcp
---
apiVersion: v1
kind: Service
metadata:
  name: imgsrvr
  labels:
    run: imgsrvr
spec:
  type: ClusterIP
  selector:
    run: imgserver
  ports:
  - name: http
    port: 9000
    targetPort: 9000
    protocol: TCP            