---           
apiVersion: apps/v1
kind: Deployment
metadata:
  name: imgserver
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
     run: imgserver
  template:
    metadata:
      labels:
        run: imgserver
    spec:
      nodeName: docker02
      containers:
      - name: iipimage
        image:  moravianlibrary/iipsrv-imageserver-opj:latest
        ports:
        - containerPort: 9000
          name: tcp
        volumeMounts:
        - name: imgserver-import
          mountPath: /data/import     
      - name: nginx
        image:  harbor.nkp.cz:30004/library/nginx:latest
        ports:
        - containerPort: 80
          name: tcp
        volumeMounts:
        - name: imgserver-import
          mountPath: /data/import           
      volumes:
       - name: imgserver-import
         hostPath:
            path: /data/import
---
apiVersion: v1               
kind: Service                
metadata:                    
  name: imgserver 
  labels:                    
    run: imgserver
spec:                        
  type: NodePort
  selector:                   
    run: imgserver
  ports:  
    - port: 80
      nodePort: 30006
      name: tcp 
---
apiVersion: v1
kind: Service
metadata:
  name: imgserver
  labels:
    service: imgserver
spec:
  type: ClusterIP
  selector:
    service: imgserver
  ports:
  - name: tcp
    port: 9000
    targetPort: 9000
    protocol: TCP