apiVersion: v1               
kind: Service                
metadata:                    
  name: solr-service 
  labels:                    
    app: solr-app
spec:                        
  type: ClusterIP
  selector:                   
    app: solr-app
  ports:                                   
  - port: 8983               
    targetPort: 8983
    protocol: TCP   