apiVersion: v1
kind: Service
metadata:
  name: my-release-zookeeper
  labels:
    app: zookeeper-app
spec:
  clusterIP: None
  selector:
    app: zookeeper-app
---
apiVersion: v1
kind: Service
metadata:
  name: zk-service
  labels:
    app: zookeeper-app
spec:
  ports:
  - port: 2181
    nodePort: 32181
    protocol: TCP
  selector:
    app: zookeeper-app
  type: NodePort
