apiVersion: v1
kind: Service
metadata:
  name: solrcluster
  namespace: zk-solr-ha
  labels:
    app: solr-app
spec:
  clusterIP: None
  selector:
    app: solr-app
---
apiVersion: v1               
kind: Service                
metadata:                    
  name: solr-np 
  namespace: zk-solr-ha
  labels:                    
    app: solr-app
spec:                        
  type: NodePort
  selector:                   
    app: solr-app
  ports:  
    - port: 8983
      nodePort: 30983
      name: http